### ISSUE TITLE
API safety concerns

### ISSUE THREAD

**Issue by kvark** [aclysma/rafx#123]
Looking through "api_triangle.rs", I see no use of `unsafe`. At the same time, the shaders are loaded from files, such as "shader.vert.metal" and "shader.vert.spv".

Is there any mechanism in place to validate the shaders provided by the user?
Is there any mechanism to prevent out-of-bound accesses for buffers and storage images?
Is the pipeline interface validated against the shader requirements?

If any of these are "no", then this becomes Undefined Behavior from Vulkan/Metal point of view, and can lead to dragons. Therefore, the relevant APIs (including the command submission) need to be qualified as `unsafe`.

**Comment by aclysma** [comment]
The entire API should be considered unsafe. I don’t plan to add any validation beyond very trivial checks (like buffer size is non-zero), and many of those will be asserts, not catchable errors.

If I followed traditional rules for when to mark a function as unsafe, every single function would be unsafe. In my opinion it would be more annoying than helpful.

There is more info in the docs:

https://github.com/aclysma/rafx/blob/master/docs/api/api_design.md#safety

https://github.com/aclysma/rafx/blob/master/docs/api/safety.md

Maybe when the library matures, we can re-evaluate this for higher level crates. But I don’t expect this will change for low level crates.

**Comment by kvark** [comment]
> If I followed traditional rules for when to mark a function as unsafe, every single function would be unsafe. In my opinion it would be more annoying than helpful.

Wouldn't the same reasoning apply to Ash, gfx-hal, and other libraries? The value of `unsafe` is much greater if it's applied consistently through the stack. Once every crate starts to decide on their own what `unsafe` means, they become un-composable, and one of the strongest aspects of Rust gets lost.

**Comment by aclysma** [comment]
* I will make initialization (`RafxApi::new`) of the API unsafe. At least this way, users have to acknowledge that that API is unsafe *somewhere*. I'll reconsider this when the library is more mature.
 * I'll add something to the readme so that this is a little more prominent.

**Comment by kvark** [comment]
Thank you!
If we are pedantic, Rust wants the libraries to require `unsafe` close where bad stuff happens, as opposed to some earlier point. This can be seen in pointers, for example, where taking an address is safe, but dereferencing is not.
But I think the steps you suggested are a reasonable compromise.

**Comment by aclysma** [comment]
PR #124
