### ISSUE TITLE
GPU instancing support in the framework & demo features

### ISSUE THREAD

**Issue by mmn80** [aclysma/rafx#129]
I was wondering what plans there are for supporting GPU instancing in the framework types. Currently it seems that you can only do it with the low level API. I have a few observations, but I'm not an expert in any of this. 

Using the vertex buffer style, the `RafxVertexAttributeRate` flag should be exposed inside `VertexDataSetLayoutInner` in `vertex_data.rs`, so that users can set it to `RafxVertexAttributeRate::Instance`, and later on `get_or_create_graphics_pipeline` would use it. This change would propagate by adding extra params to the builder in `vertex_data.rs` and so on, but it's fairly minimal I think.

Concerning the demo "mesh" feature, the PBR shader would be duplicated along it's material. This causes a problem with the GLTF importer which hardcodes the usual material, but can be overridden in the prepare job. You would perhaps have a flag in your ECS component saying "use GPU instancing" and the prepare job would group these together and override the material with the instanced variant. Duplicating shaders is messy. Maybe you could use includes or defines.

Then there is the dynamic uniform buffers method. This would have the great advantage, I belive, of reusing the shaders and materials (and descriptor sets, you'd just re-bind at a different offset), and could become an "aspect" available to all custom shaders for free, but there is that size limitation of 16384 for the buffer, if I recall correctly.

So maybe both methods could be available, the dynamic uniforms for PBR materials, where you probably do not need a very large number of instances (or you could use multiple buffers?), and exposing `RafxVertexAttributeRate` for foliage, where
you probably do not want to reuse the PBR shader anyway (but you'd still need shadows, depth prepass??).

For starters, I would like to make a PR with the exposing `RafxVertexAttributeRate` part (in case I get it working with my features) so I don't have to maintain a fork just for this until proper support is added. This seems to be in line with the style of this library (offering abstractions without hiding the low level stuff). Would that be ok?

**Comment by mmn80** [comment]
I'm closing this as it's mostly a question, better belonging to the discussions tab or a discord channel.

**Comment by aclysma** [comment]
Hey, I meant to leave a comment and forgot! Regarding instancing, I haven't personally done much with it so I don't completely confident in how it should work beyond the API level. However, I think your suggestion to add RafxVertexAttributeRate to VertexDataSetLayoutInner makes sense. Maybe we should hook it up in GraphicsPipelineCache::graphics_pipeline right before calling get_or_create_graphics_pipeline?

As far as instancing in the demo, I would expect we'd want to have an array of transform matrices (maybe some other data too) in a uniform. I could also see material definitions in an array and using a dynamic uniform to grab those. I think some of this would depend on how "modern" of a pipeline is being targeted. I'm hoping to merge a GLES 2.0 backend in the next few days and it may have limited support for some of this.

Over the next few months, I'm hoping to lock down how many "tiers" of hardware support (i.e. a basic pipeline with no compute shaders vs. a modern pipeline that does have compute shaders) we want to target.

Anyways, the PR you suggested sounds like a good change. :)

Also, questions here are fine! At some point we may enable GitHub discussions or something, but I'd like to focus on maturing the library a bit more before starting a "community." :)

**Comment by mmn80** [comment]
Thanks for answering.

> I'd like to focus on maturing the library a bit more before starting a "community. :)

That's why I closed the issue. I'm aware large refactorings are in the works (I've read all bevy discord chats etc) and do not want to interfere with my problems or PRs before this gets to that magical, most perfect & production ready 0.1 status :). I understand this is also the reason that the features in the demo are not published into their own crate, even as most users would need them.

For my project (RTS) I took inspiration from the [oxidator demo](https://github.com/Ruddle/oxidator/) which renders (`wgpu`) each independently moving part of each model GPU instanced and even with 35K models in the scene it barely registers on the CPU side and GPU is ~50%. But it's just basic blinn phong with no shadows, and shader sampled hightmap (and bulk state replication netcode). I try to recreate that within the proper pbr pipeline here (targeting what you call "modern" above) and find out what's the best way to do it. But I really don't want to obstruct library work except for that minimal PR mentioned.

**Comment by DavidVonDerau** [comment]
Re-opening to close with https://github.com/aclysma/rafx/pull/148.

**Comment by mmn80** [comment]
Clever. So you avoid allocating descriptors per instance (the most likely cause of being CPU bound) and also duplicating the shader into "shader variants", by always sending instance transforms as attributes with per instance rate, but just draw one instance in this case. The mesh feature could be generalized later for `draw_instanced`.

As a side note, I saw in `oxidator` that they reduce the size of attributes by only sending position & Euler angles and compute the `mat4` in the shader. You can avoid gimbal lock on the CPU side by adding some constraints to your game, or you can draw the locked ones in a secondary pass where you do send the `mat4`s. This would require "shader variants" though. No idea if it's worth it.

I like the material override, only wish there would also be a mesh override to support rendering procedurally generated meshes (from voxels, sdfs) without needing to add a new `distill` importer for `MeshAsset` (which could cause serialization overhead?).

Anyway, thank you DVD!
