### ISSUE TITLE
Tag The 0.0.13 Release

### ISSUE THREAD

**Issue by zicklag** [aclysma/rafx#169]
It would be useful to have a git tag on 89fb4015e83cf5f9807489cb94d2be58dca584fe for the 0.0.13 release. I was just trying to figure out how far behind the crates.io release was from master and had to look at the crates [VCS info](https://docs.rs/crate/rafx/0.0.13/source/.cargo_vcs_info.json) on docs.rs.

**Comment by aclysma** [comment]
Pushed the tag. I usually make it but forget to push it :)
