### ISSUE TITLE
Unresolved import `ash::version`

### ISSUE THREAD

**Issue by liquidev** [aclysma/rafx#179]
I just bumped skulpin in my project from 0.11.2 to 0.14.0, which means that now rafx is a dependency. It seems that the library uses some outdated APIs from ash:
```
error[E0432]: unresolved import `ash::version`
 --> C:\Users\liquid\.cargo\registry\src\github.com-1ecc6299db9ec823\rafx-api-0.0.13\src\backends\vulkan\device_context.rs:3:10
  |
3 | use ash::version::{DeviceV1_0, InstanceV1_0};
  |          ^^^^^^^ could not find `version` in `ash`

error[E0432]: unresolved import `ash::version`
 --> C:\Users\liquid\.cargo\registry\src\github.com-1ecc6299db9ec823\rafx-api-0.0.13\src\backends\vulkan\swapchain.rs:4:10
  |
4 | use ash::version::DeviceV1_0;
  |          ^^^^^^^ could not find `version` in `ash`

error[E0432]: unresolved import `ash::version`
 --> C:\Users\liquid\.cargo\registry\src\github.com-1ecc6299db9ec823\rafx-api-0.0.13\src\backends\vulkan\shader_module.rs:3:10
  |
3 | use ash::version::DeviceV1_0;
  |          ^^^^^^^ could not find `version` in `ash`
```
and so on.

[Here](https://github.com/MaikKlein/ash/issues/467)'s the related issue in ash.

**Comment by aclysma** [comment]
Rafx 0.0.14 fixes this. So it may be as simple as bumping skulpin-renderer to use 0.0.14 instead of 0.0.13. I’m on vacation so it may be a few days before I get to this. Other temporary option is to cargo update —precise to force ash down a version

**Comment by liquidev** [comment]
Thanks for the response. I've bumped ash down to 0.32, and everything works as expected.
