### ISSUE TITLE
Webgpu support

### ISSUE THREAD

**Issue by happydpc** [aclysma/rafx#181]
This project is very nice with render graph and resource pipeline. Will you plan to support wgpu backend?

**Comment by aclysma** [comment]
I think some time in the future, a webgpu backend would be an appropriate and valuable addition. However, I don't anticipate working on this personally for quite some time. The spec is in "working draft" state, and no browsers support it without turning on experimental flags. I'm personally more interested in adding DX12 support, or improving the existing backends (vulkan 1.2 features, or metal heaps, for example.)

Not to say this isn't a good idea, just being realistic and transparent about my own personal priorities/preferences. I'd be happy to help someone implement and upstream this if they were interested.
