### ISSUE TITLE
Demo won't run, stuck on "blocked waiting for asset to resolve demo font handle"

### ISSUE THREAD

**Issue by BillyDM** [aclysma/rafx#222]
I'm trying to run the demo, but upon launching it it only shows a black screen, with the terminal is constantly spitting this out:
```
INFO  rafx_assets::assets::asset_manager] blocked waiting for asset to resolve demo font Handle { handle_ref: LoadHandle(9223372036854775890) }
```

I'm running Manjaro Linux with the Budgie DE, and I'm running and AMD RX570 GPU.

**Comment by aclysma** [comment]
Did you follow these steps exactly?

https://github.com/aclysma/rafx#running-the-demo

The error sounds like the demo is being launched from the wrong dir (you have to be in the demo folder) or you might not have waited long enough (try release, the image crate is shockingly slow in debug but fine in release.)

**Comment by BillyDM** [comment]
Oh, my bad. I missed the part about needing to be launched from the demo directory.
