### ISSUE TITLE
Support for MoltenVK in Vulkan 1.3.x SDKs

### ISSUE THREAD

**Issue by ctrlcctrlv** [aclysma/rafx#237]
https://github.com/aclysma/rafx/blob/a274b82c873c0ec7f9d6c3376cd054bfccfe3895/rafx-api/src/backends/vulkan/api.rs#L51

The new VulkanSDK requires to load an extension called [VK_KHR_portability_enumeration](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_portability_enumeration.html) to use MoltenVK.

Rafx offers no way to do it. (Cf. https://github.com/aclysma/skulpin/issues/108#issuecomment-1221912763)

**Comment by aclysma** [comment]
This is a vulkan SDK 1.3 compatibility issue. I can add support for this.

**Comment by aclysma** [comment]
Apparently there is a warning for this when installing the 1.3 SDK :)

![image](https://user-images.githubusercontent.com/316070/186052218-2780c088-be72-452c-8b05-aff97916ef4e.png)

**Comment by aclysma** [comment]
Support added in #238, will need to make a new release but I'd like to double check that this doesn't break old SDKs or non-macos machines.

**Comment by ctrlcctrlv** [comment]
Thanks @aclysma. I'm going to push to MFEK/skulpin.rlib a Cargo.toml change that'll refer to 38ca251df87ce9194a6706167d3a3300307bf91d in the meantime.

**Comment by aclysma** [comment]
Released in v0.0.16
