### ISSUE TITLE
Unsound implementation in `memory::{any_as_bytes, any_slice_as_bytes}`

### ISSUE THREAD

**Issue by shinmao** [aclysma/rafx#255]
### The source of unsoundness
Hi, I am the PhD researcher from [Sun Security Lab](https://sunlab-gmu.github.io/). While we built up our tool and scanning through the libraries on crates.io, we found that your crate might include some unsound implementation:
https://github.com/aclysma/rafx/blob/65c5dc3a94782218efbf2fb61f9f903676b0a330/rafx-base/src/memory.rs#L25-L31
At line 26 and line 27, the generic type `data` was casted to `u8` type. However, there was no any appropriate trait bound applied to the generic type, so users can pass arbitrary types (e.g., with padding bytes). When the padding bytes are read as `u8` types, undefined behavior happens. Same issue could happen in `any_slice_as_bytes`.

### To reproduce the bug
```rs
use rafx_base::memory::any_as_bytes;

#[repr(align(2))]
#[derive(Copy, Clone, Debug)]
struct Padding {
    a: u8,
    b: u16,
    c: u8,
}

fn main() {
    let pd = Padding { a: 10, b: 11, c: 12 };
    let any = any_as_bytes(&pd);
    println!("{:?}", any);
}
```
to run with miri,
```
error: Undefined Behavior: using uninitialized data, but this operation requires initialized memory
   --> /${HOME}/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/num.rs:466:5
    |
466 | /     impl_Display!(
467 | |         i8, u8, i16, u16, i32, u32, i64, u64, usize, isize
468 | |             as u64 via to_u64 named fmt_u64
469 | |     );
    | |_____^ using uninitialized data, but this operation requires initialized memory
    |
    = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
```

**Comment by aclysma** [comment]
I can see the result of this being undefined in the sense that the padding bytes could be any value. I don't expect in practice this would cause real problems such as an actual crash.

This function is very much meant for low-level work with data (like memcpy of structs to GPU memory) and potentially having junk in the padding bytes would be acceptable and expected behavior.

**Comment by shinmao** [comment]
It's true that it is hard to cause to crash here. But from perspective of safety, undefined behavior is not allowed to happen in safe function anyway. From the concept of the programming language, this function should be declared as `unsafe`.

**Comment by aclysma** [comment]
As noted in the readme, this project does not follow typical guidance for the usage of unsafe. (https://github.com/aclysma/rafx#safety)
